-- ==========================================================
-- Database Schema Setup Script
-- ==========================================================

-- 1. Enable the pgvector extension
CREATE EXTENSION IF NOT EXISTS "vector";

-- 2. Create the chats table
CREATE TABLE IF NOT EXISTS public.chats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid,
  history jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- 3. Create the documents table for RAG context
CREATE TABLE IF NOT EXISTS public.documents (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  content text NOT NULL,
  metadata jsonb,
  embedding vector(768)
);

-- 4. Create the chat_messages_vectors table
CREATE TABLE IF NOT EXISTS public.chat_messages_vectors (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  chat_id bigint REFERENCES public.chats(id),
  sender text NOT NULL,
  message_text text NOT NULL,
  embedding vector(768),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. Create HNSW indexes for high-performance vector search
CREATE INDEX IF NOT EXISTS documents_embedding_idx 
ON public.documents USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS chat_messages_embedding_idx 
ON public.chat_messages_vectors USING hnsw (embedding vector_cosine_ops);

-- 6. Function to match semantic user messages across sessions
CREATE OR REPLACE FUNCTION public.match_user_messages(
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  user_id_param text
)
RETURNS TABLE (
  id bigint,
  chat_id bigint,
  sender text,
  message_text text,
  similarity float
)
AS $$
BEGIN
  RETURN QUERY
  SELECT
    v.id,
    v.chat_id,
    v.sender,
    v.message_text,
    1 - (v.embedding <=> query_embedding) AS similarity
  FROM public.chat_messages_vectors v
  INNER JOIN public.chats c ON v.chat_id = c.id
  WHERE c.user_id::text = user_id_param 
    AND 1 - (v.embedding <=> query_embedding) > match_threshold
  ORDER BY v.embedding <=> query_embedding ASC
  LIMIT match_count;
END;
$$ LANGUAGE plpgsql;

-- 7. Function to match RAG documents
CREATE OR REPLACE FUNCTION public.match_documents(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
AS $$
BEGIN
  RETURN QUERY
  SELECT
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) AS similarity
  FROM public.documents d
  WHERE 1 - (d.embedding <=> query_embedding) > match_threshold
  ORDER BY d.embedding <=> query_embedding ASC
  LIMIT match_count;
END;
$$ LANGUAGE plpgsql;